### ISSUE TITLE
Understanding TLS On Kubernetes

### ISSUE THREAD

**Issue by Yancey0623** [k8sp/issues#33]
TLS 的介绍请见 @wangkuiyi 的这个repo:https://github.com/k8sp/tls. 介绍的非常易懂。
这个issue的目标是讲清楚如何在Kubernetes集群中访问以安全的方式访问apiserver.
- [x] Kubernetes集群中的Pod是如何拿到apiserver的公钥访问https接口的
- [ ] 写一个demo程序以pod的形式提交到集群访问apiserver的https接口

**Comment by Yancey1989** [comment]
TLS 的介绍请见 @wangkuiyi 的这个repo:https://github.com/k8sp/tls. 介绍的非常易懂。
这个issue的目标是讲清楚如何在Kubernetes集群中访问以安全的方式访问apiserver.

- [ ] Kubernetes集群中的Pod是如何拿到apiserver的公钥访问https接口的
- [ ] 写一个demo程序以pod的形式提交到集群访问apiserver的https接口

**Comment by Yancey0623** [comment]
如果Pod运行在Kubernetes集群中，需要使用TLS认证机制作为kubernetes Client去访问apiserver。
这是Nginx Ingress Controller中的代码:

```
    var err error
    if *inCluster {
        kubeClient, err = unversioned.NewInCluster()
    } else {
        config, connErr := clientConfig.ClientConfig()
        if connErr != nil {
            glog.Fatalf("error connecting to the client: %v", err)
        }
        kubeClient, err = unversioned.New(config)
    }
    if err != nil {
        glog.Fatalf("failed to create client: %v", err)
    }

```

通过看到kubeClient是通过unversioned.NewInCluster()这个方法来实例化的。

下面是kubernetes中client的代码，位置在kubernetes/pkg/client/restclient.config.go#InClusterConfig()

```
func InClusterConfig() (*Config, error) {
    host, port := os.Getenv("KUBERNETES_SERVICE_HOST"), os.Getenv("KUBERNETES_SERVICE_PORT")
    if len(host) == 0 || len(port) == 0 {
        return nil, fmt.Errorf("unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined")
    }

    token, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/" + api.ServiceAccountTokenKey)
    if err != nil {
        return nil, err
    }
    tlsClientConfig := TLSClientConfig{}
    rootCAFile := "/var/run/secrets/kubernetes.io/serviceaccount/" + api.ServiceAccountRootCAKey
    if _, err := util.CertPoolFromFile(rootCAFile); err != nil {
        glog.Errorf("Expected to load root CA config from %s, but got err: %v", rootCAFile, err)
    } else {
        tlsClientConfig.CAFile = rootCAFile
    }

    return &Config{
        // TODO: switch to using cluster DNS.
        Host:            "https://" + net.JoinHostPort(host, port),
        BearerToken:     string(token),
        TLSClientConfig: tlsClientConfig,
    }, nil
}
```

能够看到实际上是load了Container中/var/run/secrets/kubernetes.io/serviceaccount/路径下的CA证书，那么这个目录中的证书是何时mount到Container中的呢？我们观察一下container的mount信息

```
        "Mounts": [
             ....
            {
                "Source": "/var/lib/kubelet/pods/d64fc7b8-4ce4-11e6-b11e-ecf4bbe48ab4/volumes/kubernetes.io~secret/default-token-u4413",
                "Destination": "/var/run/secrets/kubernetes.io/serviceaccount",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
            ...
        ]
```

通过`kubectl describe pod`
这个mount的目录是kubernetes中serviceaccount的机制来创建的，每个namespace下都会默认创建这样一个serviceaccount

参考文献:
https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/design/service_accounts.md
https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/design/secrets.md

TOOD:
了解serviceaccount的来龙去脉。

**Comment by Yancey0623** [comment]
这个Mount的目录是Kubernetes中Secret的机制来实现的，下面就介绍一下Secret

#### 什么是Secret

当用户需要在Pod中添加一些敏感的信息(例如，Token，密码等)的时候，Kubernetes设计了Secret来允许用户添加自己的敏感信息。它可以帮助用户和集群管理员制定相关的安全策略
1. 在pod启动之后添加**.kubeconfig**，**.dockercfg**等文件，以便访问一些需要认证的服务
2. 使用认证从一些私有的docker registry上pull pod的image.

#### Secret的三种类型
1. Opaque, 为任意的数据类型,默认为此类型
2. kubernetes.io/service-account-token, Kubernetes认证的Token
3. kubernetes.io/dockercfg, Docker Registry的认证信息

#### 如何使用Secret

用户可以通过kubectl命令创建自己的secret，kubernetes默认也会添加一些secret。
- 创建一个secret,注意**认证数据必须为base64编码**

```
yancey@ yancey-macbook quota$cat username-secret.yaml
{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "user-secret"
  },
  "data": {
    "username": "YWRtaW4K",
    "password": "cGFzc3dvcmQK"
  }
}
yancey@ yancey-macbook quota$kubectl create -f username-secret.yaml
secret "user-secret" created
```
- 在pod中使用这个secret

```
yancey@ yancey-macbook webapp$cat rc-hello.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: hello
  labels:
    component: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: hello
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: "user-secret"
      containers:
      - name: hello
        image: yancey1989/hello:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: /etc/user-password
yancey@ yancey-macbook webapp$kubectl create -f rc-hello.yaml
yancey@ yancey-macbook webapp$kubectl exec hello-islfo cat /etc/user-password/username
admin
```

#### 关于在Kubernetes集群中连接apiserver的secret接口
- Kubernetes会为每个namespace创建一个默认的secret,这里面会包括`ca.crt`的数据

```
yancey@ yancey-macbook github.com$kubectl get secret default-token-u4413
NAME                  TYPE                                  DATA      AGE
default-token-u4413   kubernetes.io/service-account-token   3         2d
yancey@ yancey-macbook github.com$kubectl get secret default-token-u4413 -o yaml
apiVersion: v1
data:
  ca.crt: LS0...Cg==
  namespace: ZGV...==
  token: ZXlKaGJHY...F9ZaXR3
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: e7099067-4cb9-11e6-882f-ecf4bbe48ab4
  creationTimestamp: 2016-07-18T07:33:21Z
  name: default-token-u4413
  namespace: default
  resourceVersion: "10960"
  selfLink: /api/v1/namespaces/default/secrets/default-token-u4413
  uid: e70cd550-4cb9-11e6-882f-ecf4bbe48ab4
type: kubernetes.io/service-account-token 
```
- Kubernetes会默认在启动Pod时使用这个Secret，将cat.cart等文件挂在到Pod的/var/run/secrets/kubernetes.io/serviceaccount目录下
  通过查看pod的描述信息可以看到:

```
yancey@ yancey-macbook github.com$kubectl get pod nginx-ingress-controller-ypi9d -o yaml
apiVersion: v1
kind: Pod
    ...
spec:
  containers:
    ...
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-u4413
      readOnly: true
    ...
  volumes:
  - name: default-token-u4413
    secret:
      secretName: default-token-u4413
status:
    ...
```
- 使用`kubecl exec`命令能够看到相关证书的文件，在pod中使用https客户端中直接load证书即可实现对kubernetes secret api的访问

```
yancey@ yancey-macbook kubernetes-examples$kubectl exec nginx-ingress-controller-ypi9d ls /var/run/secrets/kubernetes.io/serviceaccount
ca.crt
namespace
token
```

Task1 done.
TODO: 写一个运行在kubernetes集群上的https客户端，并且能够和kubernetes api的secret接口通信。

**Comment by Yancey1989** [comment]
这个Mount的目录是Kubernetes中Secret的机制来实现的，下面就介绍一下Secret


#### 什么是Secret

当用户需要在Pod中添加一些敏感的信息(例如，Token，密码等)的时候，Kubernetes设计了Secret来允许用户添加自己的敏感信息。它可以帮助用户和集群管理员制定相关的安全策略

1. 在pod启动之后添加**.kubeconfig**，**.dockercfg**等文件，以便访问一些需要认证的服务
2. 使用认证从一些私有的docker registry上pull pod的image.

#### Secret的三种类型


1. Opaque, 为任意的数据类型,默认为此类型
2. kubernetes.io/service-account-token, Kubernetes认证的Token
3. kubernetes.io/dockercfg, Docker Registry的认证信息

#### 如何使用Secret

用户可以通过kubectl命令创建自己的secret，kubernetes默认也会添加一些secret。

* 创建一个secret,注意**认证数据必须为base64编码**

```
yancey@ yancey-macbook quota$cat username-secret.yaml
{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "user-secret"
  },
  "data": {
    "username": "YWRtaW4K",
    "password": "cGFzc3dvcmQK"
  }
}
yancey@ yancey-macbook quota$kubectl create -f username-secret.yaml
secret "user-secret" created
```

* 在pod中使用这个secret


```
yancey@ yancey-macbook webapp$cat rc-hello.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: hello
  labels:
    component: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: hello
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: "user-secret"
      containers:
      - name: hello
        image: yancey1989/hello:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: /etc/user-password
yancey@ yancey-macbook webapp$kubectl create -f rc-hello.yaml
yancey@ yancey-macbook webapp$kubectl exec hello-islfo cat /etc/user-password/username
admin
```

#### 关于在Kubernetes集群中连接apiserver的secret接口

* Kubernetes会为每个namespace创建一个默认的secret,这里面会包括```ca.crt```的数据

```
yancey@ yancey-macbook github.com$kubectl get secret default-token-u4413
NAME                  TYPE                                  DATA      AGE
default-token-u4413   kubernetes.io/service-account-token   3         2d
yancey@ yancey-macbook github.com$kubectl get secret default-token-u4413 -o yaml
apiVersion: v1
data:
  ca.crt: LS0...Cg==
  namespace: ZGV...==
  token: ZXlKaGJHY...F9ZaXR3
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: e7099067-4cb9-11e6-882f-ecf4bbe48ab4
  creationTimestamp: 2016-07-18T07:33:21Z
  name: default-token-u4413
  namespace: default
  resourceVersion: "10960"
  selfLink: /api/v1/namespaces/default/secrets/default-token-u4413
  uid: e70cd550-4cb9-11e6-882f-ecf4bbe48ab4
type: kubernetes.io/service-account-token 
```
* Kubernetes会默认在启动Pod时使用这个Secret，将cat.cart等文件挂在到Pod的/var/run/secrets/kubernetes.io/serviceaccount目录下
通过查看pod的描述信息可以看到:

```
yancey@ yancey-macbook github.com$kubectl get pod nginx-ingress-controller-ypi9d -o yaml
apiVersion: v1
kind: Pod
	...
spec:
  containers:
  	...
  	volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-u4413
      readOnly: true
	...
  volumes:
  - name: default-token-u4413
    secret:
      secretName: default-token-u4413
status:
	...
```

* 使用```kubecl exec```命令能够看到相关证书的文件，在pod中使用https客户端中直接load证书即可实现对kubernetes secret api的访问

```
yancey@ yancey-macbook kubernetes-examples$kubectl exec nginx-ingress-controller-ypi9d ls /var/run/secrets/kubernetes.io/serviceaccount
ca.crt
namespace
token
```
