### ISSUE TITLE
access Docker Registry using credentials from a dockercfg via Kubernetes

### ISSUE THREAD

**Issue by LestDou** [k8sp/issues#34]
Due to the pod should  get images from our private registry through BA , we'd not do this manually, test how to use dockercfg(~/.docker/config.json or something like this) on k8s is needed.

**Comment by LestDou** [comment]
Info from (http://kubernetes.io/docs/user-guide/secrets/)
we can store BA informations in kube(etcd actually)

``` sh
lest@lest-ThinkPad-S5-S531:~/lestgit/coreos-vagrant$ kubectl get secret
NAME                  TYPE                                  DATA      AGE
default-token-60khf   kubernetes.io/service-account-token   3         1d
myregistrykey         kubernetes.io/dockercfg               1         23h
```

command for create it:
`kubectl create secret docker-registry myregistrykey --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL`

call it from yaml:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: docker.baifendian.com/lifeng.zhang/nginx
    ports:
    - containerPort: 80
  imagePullSecrets:
    - name: myregistrykey
```

successfully pulled image from registry through BA

``` bash
lest@lest-ThinkPad-S5-S531:~/yaml$ kubectl describe pod nginx
Name:       nginx
Namespace:  default
Node:       core-02/172.17.8.102
Start Time: Thu, 21 Jul 2016 18:52:02 +0800
Labels:     app=nginx
Status:     Running
IP:     10.1.88.3
Controllers:    <none>
Containers:
  nginx:
    Container ID:   docker://f31c6e75ecb6e2796cdcdec01d8e9b1b58588061b754537a53e0789901eef532
    Image:      docker.baifendian.com/lifeng.zhang/nginx
    Image ID:       docker://sha256:baf849297a90f25eb8257b651e9241af6b48e298e8261df7dea8894d768c18a7
    Port:       80/TCP
    QoS Tier:
      cpu:      BestEffort
      memory:       BestEffort
    State:      Running
      Started:      Thu, 21 Jul 2016 18:52:11 +0800
    Ready:      True
    Restart Count:  0
    Environment Variables:
Conditions:
  Type      Status
  Ready     True 
Volumes:
  default-token-60khf:
    Type:   Secret (a volume populated by a Secret)
    SecretName: default-token-60khf
No events.
```
