### ISSUE TITLE
Deploy kubernetes and ingress with two network card

### ISSUE THREAD

**Issue by Yancey0623** [k8sp/issues#37]
flanneld在启动时需要指定iface为内网地址的网卡，如果不指定，flannel启时默认会选择默认网关绑定的那块网卡,代码:https://github.com/coreos/flannel/blob/master/pkg/ip/iface.go#L85

```
func GetDefaultGatewayIface() (*net.Interface, error) {
...
  for _, route := range routes {
    if route.Dst == nil || route.Dst.String() == "0.0.0.0/0" {
      if route.LinkIndex <= 0 {
        return nil, errors.New("Found default route but could not determine interface")
      }
      return net.InterfaceByIndex(route.LinkIndex)
    }
  }
...
}
```

如果当前机器默认网关绑定的是External IP所在的网卡，则会出现启动失败的情况.在cc文件中加入flanneld的启动参数的方法如下:

```
coreos:
  flannel:
    etcd_endpoints: "http://infra0:2379,http://infra1:2379,http://infra2:2379"
    interface: "bond0"
...
```
